name = "kaisar"
main = "build/worker/shim.mjs"
compatibility_date = "2024-05-23"
minify = true
workers_dev = true

routes = [
  { pattern = "pro.kopralstore.my.id", custom_domain = true },
  { pattern = "ava.game.naver.com.pro.kopralstore.my.id", custom_domain = true },
  { pattern = "df.game.naver.com.pro.kopralstore.my.id", custom_domain = true },
  { pattern = "graph.instagram.com.pro.kopralstore.my.id", custom_domain = true },
  { pattern = "zaintest.vuclip.com.pro.kopralstore.my.id", custom_domain = true },
  { pattern = "support.zoom.us.pro.kopralstore.my.id", custom_domain = true },
  { pattern = "cache.netflix.com.pro.kopralstore.my.id", custom_domain = true },

  { pattern = "gacor.kopralstore.my.id", custom_domain = true },
  { pattern = "ava.game.naver.com.gacor.kopralstore.my.id", custom_domain = true },
  { pattern = "df.game.naver.com.gacor.kopralstore.my.id", custom_domain = true },
  { pattern = "graph.instagram.com.gacor.kopralstore.my.id", custom_domain = true },
  { pattern = "zaintest.vuclip.com.gacor.kopralstore.my.id", custom_domain = true },
  { pattern = "support.zoom.us.gacor.kopralstore.my.id", custom_domain = true },
  { pattern = "cache.netflix.com.gacor.kopralstore.my.id", custom_domain = true }
]

[[kv_namespaces]]
binding = "SIREN"
id = "c598b08770654155ac40773492c1f0d5"

[build]
command = "cargo install -q worker-build && worker-build --release"

[env.dev]
build = { command = "cargo install -q worker-build && worker-build --dev" }

[vars]
UUID = "f282b878-8711-45a1-8c69-5564172123c1"
MAIN_PAGE_URL = "https://raw.githubusercontent.com/KopralProject/vpn-cf/refs/heads/master/web/index.html"
SUB_PAGE_URL  = "https://raw.githubusercontent.com/KopralProject/vpn-cf/refs/heads/master/web/sub.html"
LINK_PAGE_URL = "https://raw.githubusercontent.com/KopralProject/vpn-cf/refs/heads/master/web/link.html"
