name = "baru"
main = "build/worker/shim.mjs"
compatibility_date = "2024-05-23"
minify = true
workers_dev = true

routes = [
  { pattern = "sunda.pasarbanjar.web.id", custom_domain = true },
  { pattern = "ava.game.naver.com.sunda.pasarbanjar.web.id", custom_domain = true },
  { pattern = "df.game.naver.com.sunda.pasarbanjar.web.id", custom_domain = true },
  { pattern = "graph.instagram.com.sunda.pasarbanjar.web.id", custom_domain = true },
  { pattern = "zaintest.vuclip.com.sunda.pasarbanjar.web.id", custom_domain = true },
  { pattern = "support.zoom.us.sunda.pasarbanjar.web.id", custom_domain = true },
  { pattern = "cache.netflix.com.sunda.pasarbanjar.web.id", custom_domain = true },

  { pattern = "pro.pasarbanjar.web.id", custom_domain = true },
  { pattern = "ava.game.naver.com.pro.pasarbanjar.web.id", custom_domain = true },
  { pattern = "df.game.naver.com.pro.pasarbanjar.web.id", custom_domain = true },
  { pattern = "graph.instagram.com.pro.pasarbanjar.web.id", custom_domain = true },
  { pattern = "zaintest.vuclip.com.pro.pasarbanjar.web.id", custom_domain = true },
  { pattern = "support.zoom.us.pro.pasarbanjar.web.id", custom_domain = true },
  { pattern = "cache.netflix.com.pro.pasarbanjar.web.id", custom_domain = true }
]

[[kv_namespaces]]
binding = "SIREN"
id = "9cf6e245587040798b755d1310842b61"

[build]
command = "cargo install -q worker-build && worker-build --release"

[env.dev]
build = { command = "cargo install -q worker-build && worker-build --dev" }

[vars]
UUID = "f282b878-8711-45a1-8c69-5564172123c1"
MAIN_PAGE_URL = "https://raw.githubusercontent.com/Dianamons/vpn-cf/refs/heads/master/web/index.html"
SUB_PAGE_URL  = "https://raw.githubusercontent.com/Dianamons/vpn-cf/refs/heads/master/web/sub.html"
LINK_PAGE_URL = "https://raw.githubusercontent.com/Dianamons/vpn-cf/refs/heads/master/web/link.html"
